POST http://localhost:5000/todo
Content-Type: application/json

{
    "title": "Make up your bed",
    "description": "Every morning you need to make up your bed",
    "startDateTime": "2024-03-08T08:00:00",
    "endDateTime": "2025-04-08T09:00:00",
    "priority" : [
        "low"
    ],
    "tags": [
        "bed",
        "sleep",
        "mood",
        "order"
    ]
}
